class Data:
  def __init__(self, shmem_buffer):
    self.buffer = buffer(shmem_buffer)
  # uint8_t firmwareIdent;
  # uint8_t status;
  # bool heartbeat;
  # int16_t Motor1;
  # int16_t Motor2;
  # int16_t Motor3;
  # int16_t Motor4;
  # int16_t Motor5;
  # int16_t Motor6;
  # uint16_t batteryMillivolts;
  # bool resetEncoder1;
  # bool resetEncoder2;
  # bool resetEncoder3;
  # bool resetEncoder4;
  # bool resetEncoder5;
  # bool resetEncoder6;
  # int16_t Encoder1;
  # int16_t Encoder2;
  # int16_t Encoder3;
  # int16_t Encoder4;
  # int16_t Encoder5;
  # int16_t Encoder6;
